name: Reusable workflow example

on:
  workflow_call:
    inputs: 
      name:
        type: string
        default: 'monalisa'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world'     
      
  example_job2:
    uses: cschleiden/cschleiden-called/.github/workflows/called2.yml@main
