name: Reusable workflow example

on:
  workflow_call:
  
concurrency: wf

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world'     
      
  example_job2:
    runs-on: ubuntu-latest
    needs: example_job
    steps:
      - run: sleep 60
